### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by 1tecumseh** [CravingCrates/AnkiCollab-Plugin#10] opened 2023-08-13 17:05 UTC
Beim Laden von '⁨AnkiCollab - The free collaboration Platform⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 230, in loadAddons
  File "/home/admin/.local/share/Anki2/addons21/1957538407/__init__.py", line 1, in <module>
    from .main import *
  File "/home/admin/.local/share/Anki2/addons21/1957538407/main.py", line 20, in <module>
    from .menu import *
  File "/home/admin/.local/share/Anki2/addons21/1957538407/menu.py", line 9, in <module>
    from .export_manager import *
  File "/home/admin/.local/share/Anki2/addons21/1957538407/export_manager.py", line 19, in <module>
    from .google_drive_api import GoogleDriveAPI
  File "/home/admin/.local/share/Anki2/addons21/1957538407/google_drive_api.py", line 13, in <module>
    from googleapiclient.http import MediaFileUpload
  File "/home/admin/.local/share/Anki2/addons21/1957538407/dist/googleapiclient/http.py", line 49, in <module>
    from email.mime.multipart import MIMEMultipart
ModuleNotFoundError: No module named 'email.mime'
⁩

What to do now? I already reinstalled the plugin.

**Comment by CravingCrates** [comment] 2023-08-13 17:39
Hello, can you please give me more information:
- What operating system do you use
- What Anki Version (and python version) do you have installed?

Haven't experienced this issue with neither Windows nor Mac nor Ubuntu so it gotta be some incompatibility

**Comment by 1tecumseh** [comment] 2023-08-14 05:31
Thanks for your reply. I am using Fedora 38, ⁨Anki 2.1.49 and Python 3.8.1 Qt 5.15.1 PyQt 5.15.1.

**Comment by eneller** [comment] 2023-08-14 09:34
```
When loading '⁨AnkiCollab - The free collaboration Platform⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/addons.py", line 246, in loadAddons
    __import__(addon.dir_name)
  File "/home/en/.local/share/Anki2/addons21/1957538407/__init__.py", line 1, in <module>
    from .main import *
  File "/home/en/.local/share/Anki2/addons21/1957538407/main.py", line 20, in <module>
    from .menu import *
  File "/home/en/.local/share/Anki2/addons21/1957538407/menu.py", line 9, in <module>
    from .export_manager import *
  File "/home/en/.local/share/Anki2/addons21/1957538407/export_manager.py", line 23, in <module>
    from .crowd_anki.anki.adapters.note_model_file_provider import NoteModelFileProvider
  File "/home/en/.local/share/Anki2/addons21/1957538407/crowd_anki/__init__.py", line 5, in <module>
    from . import main
  File "/home/en/.local/share/Anki2/addons21/1957538407/crowd_anki/main.py", line 6, in <module>
    from .anki.hook_vendor import HookVendor
  File "/home/en/.local/share/Anki2/addons21/1957538407/crowd_anki/anki/hook_vendor.py", line 12, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1223, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class '1957538407.crowd_anki.anki.adapters.hook_manager.AnkiHookManager'> for field hook_manager is not allowed: use default_factory
```

I am not familiar with the codebase or development for anki, but the occurrence of the errors in quick succession suggests they were introduced by a recent commit? Also i saw that you are committing directly to main, which is discouraged for production code. You might consider using "feature-branches" or a general development branch.

For more long-term development, Id be happy to contribute. Hope to talk to you on discord.

**Comment by CravingCrates** [comment] 2023-08-16 16:04
These issues are unrelated and neither has anything to do with a recent commit.
The first issue could potentially be linked to a faulty Python installation or a similar underlying factor (don't see how a missing default python module can be caused or fixed by my addon).

As for your issue, it appears to be separate as well. Unfortunately, without additional context, I'm unable to reproduce the problem or provide a meaningful solution.

Regarding your question about why I push to the 'main' branch: Simply because thats all you see. I am currently the only developer of this project and nobody has made any attempts so far to join me so I have a seperate development repo where I handle staging activities and this serves as the production repo.

If you could share more details, preferably with reproducible steps, it would greatly aid in resolving the issue. I'm available to provide assistance in any way I can.

I'm looking forward to connecting with you on Discord!

**Closed** 2023-09-26 09:13 UTC
